name: Create Release
on: 
  push:
    tags:
      - "v*.*.*"


jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build musl cross compiler
        run: |
          set -ex
          make TARGET=aarch64-linux-musl install
          tar -cf output artifacts.tar.gz
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts.tar.gz"
